### ISSUE TITLE
Errors creating kubernetes/conf/examples

### ISSUE THREAD

**Issue by beeva-enriqueotero** [SeldonIO/seldon-server#18]
When I try `kubectl create -f import-data-job.json` I get the following error: 

`could not read an encoded object from import-data-job.json: API version "batch/v1" in "import-data-job.json" isn't supported, only supports API versions ["v1"]`

Same thing happens with `examples/ml100k/ml100k-import.json`. Any hint about this issue?

Anyway this new dockerized architecture seems great! Thank you!

**Comment by cliveseldon** [comment]
What version of kubernetes are you running? You need version >=1.2 of kubernetes.

**Comment by beeva-enriqueotero** [comment]
Oops, I was using kubernetes 1.0.1. Solved by updating to 1.2.4! 
Thanks!

**Comment by cliveseldon** [comment]
Glad its working. We welcome further feedback and comments.

**Comment by beeva-enriqueotero** [comment]
Hello again,

Trying `kubectl create -f ml100k-import.json` I realized this job finishes as successful even in case of errors.

I test with `seldon-cli api --client-name ml100k --endpoint /js/recommendations --item 50 --limit 4` but I get no answers: 
`{"size":0,"requested":4,"list":[]}`

**Comment by cliveseldon** [comment]
Can you do a kubectl log of the job and post the output?
Can you exec into the seldon-server container and report what /home/seldon/logs/base/api.log reports when you do an api call?

**Comment by beeva-enriqueotero** [comment]
After I execute the previous API call with no results I check the logs with:

`kubectl logs seldon-server-613392384-sqs1n td-agent`

and I get:
`2016-05-27 12:31:35 +0000 [warn]: pattern not match: "2016,05,27,12,31,35,IMP,ml100k,,-1,1,2,50,0,,-,null"`

**Comment by cliveseldon** [comment]
I think there is a fix for this is the upcoming release. You can fix it by hand by removing all files under  /seldon-data/seldon-models/ml100k (or whereever your persistent storage is placed for seldon-data/seldon-models). Then rerun the steps for the ml100k example.

**Comment by beeva-enriqueotero** [comment]
Hi again,

I have further info about errors with ml100k example. Some related to problems with storage and file paths:

- I think the main cause of errors I get is that `/seldon-data` in my seldon-server is empty. There is no `seldon-models`.
- Moreover when I try to add similar-items model I get another error because of a default wrong path (SimilarItemsConfig points to `/seldon-models/` instead of `/seldon-data/seldon-models`)
- And furthermore by using local storage instead of hdfs, spark reports `FileNotFoundException` when trying to train a new model

**Comment by cliveseldon** [comment]
Hi,
We have a new update 1.3.2 that should help for repeatable running of Seldon between seldon-down/seldon-up and fix some ml100k example issues.
 Can you tell us what persistent storage for Kubernetes you are using? 
You are running the similar-items via the luigi Job in kubernetes/conf/models?

**Comment by beeva-enriqueotero** [comment]
Hi,

I will checkout this new version and let you know!

By the way I was using GlusterFS for persistent storage. And trying to add similar-items via luigi job in kubernetes/conf/models.

**Comment by beeva-enriqueotero** [comment]
I've tried release 1.3.2 with similar results: job `ml100k-import` as successful but recommender gets no answers.

`kubectl logs ml100k-import-xjp4u` shows the following error:
`IOError: [Errno 2] No such file or directory: u'/seldon-data/conf/zkroot/config/dbcp/_data_'`

**Comment by cliveseldon** [comment]
Hi,

 Can you confirm the /seldon-data is accessible on glusterfs. If so, then it sounds like the core setup has failed to create correct folders on seldon-up.

**Comment by beeva-enriqueotero** [comment]
Sometimes /seldon-data is empty after seldon-up. I've also tried without enabling GlusterFS with no success.

Sometimes /seldon-data is not empty but the ml100k recommender still gets no answers

**Comment by cliveseldon** [comment]
Are you running a multi-node cluster?
If so then glusterFs is the only option.

**Comment by beeva-enriqueotero** [comment]
Yes. I'm running a kubernetes cluster in AWS with 3 nodes (+master) and glusterfs.

**Comment by beeva-enriqueotero** [comment]
Hi,

I've realized that `/seldon-data` volume has different content in seldon-server and seldon-control pods. Is it normal?

```
$> MYSELDONSERVER=$(kubectl get pods | grep seldon-server | cut -d' ' -f1)

$> kubectl exec $MYSELDONSERVER ls /seldon-data
grafana
influxdb

$> kubectl exec seldon-control ls /seldon-data
conf
grafana
influxdb
logs
mysql
seldon-models

```

**Comment by cliveseldon** [comment]
No they should be the same.

**Comment by beeva-enriqueotero** [comment]
Hi Clive

Thanks for updating the docs about [GlusterFS installation](http://docs.seldon.io/glusterfs.html). Now it seems my Seldon cluster is working ok with GlusterFS.

To achieve this I had to uncomment `DATA_VOLUME="glusterfs"...` line in Makefile.
