### ISSUE TITLE
Setting dimensions

### ISSUE THREAD

**Issue by boogardgodig** [SeldonIO/seldon-server#24]
Hi

I have a string attribute for my items which I can probably change to enum. How can I set dimensions for my items based on that? Will seldon automatically generate dimensions if i manually alter items table in database and change type of that column?

**Comment by boogardgodig** [comment]
I had to insert (attr_id, enum_index, enum_value) to item_attr_enum and then inserted (item_type, attr_id, enum_value_id(from item_attr_enum table)) into dimension table to get it working. I wrote a little python script to extend dimensions i can provide if anyone else has the same problem.

**Comment by gsunner** [comment]
Hi, Thanks for reporting this. We did investigate your original issue re: setting dimensions and found that the seldon-cli could be improved as a result.
Yes, it possible to set the attributes and the dimensions will automatically be generated. However in the current release - it is not obvious what those dimensions are.
The seldon-cli and docs will be updated in the next release to show this.

- Gurminder
