### ISSUE TITLE
Ignored parameters in ItemSimilaritySparkJob

### ISSUE THREAD

**Issue by beeva-enriqueotero** [SeldonIO/seldon-server#25]
Hello,

It seems that sortAndLimit(..) method in SimilarItems.scala hardcodes limit parameter with value 100. So parameterization via luigi/spark.py parameters is overriden.

Moreover luigi/spark.py doesn't provide default value for 'sample' parameter in ItemSimilaritySparkJob.

**Comment by cliveseldon** [comment]
Thanks. We'll update and fix these and make a bug fix release.
