### ISSUE TITLE
minikube json validation error

### ISSUE THREAD

**Issue by geoHeil** [SeldonIO/seldon-server#26]
Minikube complains about a json validation error for mysql in the latest released version.

`error validating "/seldon-server/kubernetes/bin/../conf/mysql.json": error validating data: [unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object]; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by cliveseldon** [comment]
Can you clarify the version of minikube and Seldon you are using so we can recreate this? Thanks.

**Comment by geoHeil** [comment]
I used the latest download from github v0.12.0 https://github.com/kubernetes/minikube/releases/tag/v0.12.0

**Comment by cliveseldon** [comment]
Hi. This looks like it could be a kubectl version issue. Can you show what you get back with:
kubectl version

**Comment by geoHeil** [comment]
kubectl version
`Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}`

**Comment by cliveseldon** [comment]
Can you try upgrading your kubectl to latest and retrying?, e.g.:

kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}

**Comment by geoHeil** [comment]
sorry. Indeed you are correct. I was using an outdated kubectl.

**Comment by cliveseldon** [comment]
Great. We'll update our docs as minikube don't make it clear the issues that could happen if you already have a preexisting kubectl. Thanks for highlighting this.
