### ISSUE TITLE
Sledon-cli

### ISSUE THREAD

**Issue by michaltrmac** [SeldonIO/seldon-server#31]
Is there some command to delete client, user or item? I don't find nothing in docs.
What if I want to delete item which was removed from my app?

**Comment by gsunner** [comment]
Hi,

Currently for client/user/item there is no delete command as they are logged and may be needed for auditing.
It's functionality will look at in the future.

- Gurminder

**Comment by michaltrmac** [comment]
Hi,

thanks for quick reply. 

So how can I filter out items which is deleted from my app, from recommendation?
Because if I don't delete this items from seldon I wil have lots of results pointing to deleted items.

mt

**Comment by cliveseldon** [comment]
Hi,

 You can create in your meta data a "enum" type which is set for each item.
 In http://docs.seldon.io/content-recommendation-guide.html#client it would be the example:
 {"name":"genre","value_type":["pop","rock","rap"]},
In your case maybe
{"name":"active","value_type":["active","deleted"]},

You can set this meta data when adding items and update it when items are "deleted".
In recommendation calls you can use the "dims" attribute to restrict recommendations to a particular "dimension". There will be a dimension for each possible value of an enum type. In your case "active" and "deleted". At present the seldon-cli lacks a way to view these so you will need to log into the mysql db that holds the meta data and view the dimension table to get the correct one to pass in on your recommendation calls to get just "active" items returned in your recommendations.

**Comment by michaltrmac** [comment]
@cliveseldon thanks for the example

mt.
