### ISSUE TITLE
Could not load [org.apache.zookeeper.server.ZooTrace]

### ISSUE THREAD

**Issue by Rocknpools** [SeldonIO/seldon-server#42]
Hi everyone. I got this error while deploying seldon-server 1.3.11 outside Kubernetes.

This is not the first time i deploy seldon outside kubernetes and i never had problem.

Can someone help me?

17-Feb-2017 11:13:45.366 INFO [localhost-startStop-2] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/vagrant/apps/tomcat/webapps/seldonversion.war
17-Feb-2017 11:14:00.873 SEVERE [localhost-startStop-2] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
17-Feb-2017 11:14:00.874 SEVERE [localhost-startStop-2] org.apache.catalina.core.StandardContext.startInternal Context [/seldonversion] startup failed due to previous errors
17-Feb-2017 11:14:00.950 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [seldonversion] appears to have started a thread named [localhost-startStop-2-SendThread(172.17.0.4:2181)] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 org.apache.zookeeper.ClientCnxnSocketNIO.cleanup(ClientCnxnSocketNIO.java:219)
 org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1157)
 org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1109)
17-Feb-2017 11:14:00.959 INFO [localhost-startStop-2] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/vagrant/apps/tomcat/webapps/seldonversion.war has finished in 15,592 ms
17-Feb-2017 11:14:01.037 INFO [localhost-startStop-2-SendThread(172.17.0.4:2181)] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.apache.zookeeper.server.ZooTrace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.zookeeper.server.ZooTrace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1353)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1341)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1206)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1115)

**Comment by cliveseldon** [comment]
This generally means Zookeeper was not running or the server could not connect to Zookeeper.

**Comment by Rocknpools** [comment]
zookeeper is running because i'm able to use the pyseldon shell.

**Comment by cliveseldon** [comment]
Ok then it means there was another exception at startup that meant the server was not able to start.
Is there any other exception in the api.log earlier?

**Comment by Rocknpools** [comment]
should i initialize memcached or doing something else with the pyseldon shell before the deploying step?

**Comment by cliveseldon** [comment]
You should certainly have the other components needed by the server running. So memcached and MySQL database.
