### ISSUE TITLE
recommendation filtering by dimension with MF

### ISSUE THREAD

**Issue by Rocknpools** [SeldonIO/seldon-server#46]
Hi everyone.
I got this error when i try to filter a recommendation from the MF alg

2017-03-09 15:38:05,055 DEBUG http-nio-8080-exec-132 UserDimensionMappingModelManager [user1] [10206938095543821] [] - dimensions in: [74]
2017-03-09 15:38:05,055 DEBUG http-nio-8080-exec-132 UserDimensionMappingModelManager [user1] [10206938095543821] [] - No mappings for client[user1]
2017-03-09 15:38:05,055 DEBUG http-nio-8080-exec-132 UserDimensionMappingModelManager [user1] [10206938095543821] [] - dimensions out: [74]

Otherwise if i use a recentItems recommendation al the dimensions works correctly
Can someone explain what this log means?

**Comment by gsunner** [comment]
Hi,

It's possible to map dimension values if needed.

By default it does no mapping, so as in this debug message the dimension value [74] is passed through unchanged.

Just to check, have you setup dimension mapping for this client "user1"?

Otherwise you can ignore this debug message.

Hope this helps,

Gurminder

**Comment by Rocknpools** [comment]
Thanks @gsunner.
Exactly what do you mean with "setup the dimension mapping for a user"?
Could you link a reference from the Documentations?

**Comment by Rocknpools** [comment]
Is it a zookeeper setup?

**Comment by gsunner** [comment]
Yes, the configuration will be in zookeeper.
Unfortunately no docs on this feature yet, will look to add the relevant docs in the next set of documentation updates.

**Comment by Rocknpools** [comment]
@gsunner thanks for the replay. Could you give me some quick hints about the configuration?

**Comment by cliveseldon** [comment]
There are two classes that handle deimension mapping.
One for Locales to allow a dimension switch based on incoming locale parameter.
This can be found in io.seldon.api.locale.DimensionsMappingManager and its value is a JSON object in Zookeeper roughly of the form {"mappings_by_locale":{"ae-ar":{"1":"6204",...},...etc}

https://github.com/SeldonIO/seldon-server/blob/master/server/src/io/seldon/api/locale/DimensionsMappingManager.java

Then there is user dimensions mapping to change a dimension for particular users. This loads its config from file URI. This can be found in io.seldon.recommendation.userdimensionmapping. UserDimensionMappingModelManager

https://github.com/SeldonIO/seldon-server/blob/master/server/src/io/seldon/recommendation/userdimensionmapping/UserDimensionMappingModelManager.java


Hope that helps
