### ISSUE TITLE
kubernetes yamls should use Deployments not raw Pods

### ISSUE THREAD

**Issue by colemickens** [SeldonIO/seldon-server#49]
I deleted a Pod to try to kick it to get it to start properly. Much to my surprise... it simply didn't come back. Why is it not using a Deployment?

**Comment by colemickens** [comment]
This would also help `seldon-up` be idempotent.

**Comment by cliveseldon** [comment]
Thanks. We'll look into changing all components to be deployments as suggested.

**Comment by cliveseldon** [comment]
Fixed in release v1.4.4.
