### ISSUE TITLE
kubernetes yamls should utilize a default storage class

### ISSUE THREAD

**Issue by colemickens** [SeldonIO/seldon-server#50]
Seldon should consider just using a PVC without a PV to let the a PV be created using the user's cluster's default storage class.

This would make it trivial to deploy in a number of environments where PV provisioning is available without needing to put more yaml in an environment variable.

**Comment by tondonia** [comment]
Thanks. We'll look into making this change for next release.

**Comment by cliveseldon** [comment]
fixed in release v1.4.4
