### ISSUE TITLE
Custom prediction output

### ISSUE THREAD

**Issue by rmdort** [SeldonIO/seldon-server#51]
Can seldon be used to output prediction in any JSON format? My model outputs predictions as well other custom data.

Can i change this below format to anything i want?

````
{
  "predictions": [
    {
      "score": 0.9,
      "classId": "1",
      "confidence":0.7
    }
  ]
}
````

**Comment by cliveseldon** [comment]
Hi,

 You can send additional information in a custom field in the JSON. This is
illustrated in the gRPC section of the docs http://docs.seldon.io/grpc.html
but applies also to JSON responses.

 Clive
